name: Expo CI

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout project repository - != next
      if: "!endsWith(github.ref, '/next')"
      uses: actions/checkout@v2

    - name: Checkout project repository - == next
      if: endsWith(github.ref, '/next')
      uses: actions/checkout@v2
      with:
        fetch-depth: 255

    - name: Setup kernel for react native, increase watchers
      run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install, build and test
      run: npm ci && npm test

    - name: Login into Expo
      run: npx expo-cli login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}

    - name: Evaluate version
      id: version
      run: |
        /bin/bash --noprofile --norc ./.github/workflows/expo-build-number.sh

    - name: Publish & build with Expo channel "default"
      if: endsWith(github.ref, '/main')
      env:
        EXPO_BUILDNUMBER: ${{ steps.version.outputs.buildNumber }}
        EXPO_VERSIONCODE: ${{ steps.version.outputs.versionCode }}
      run: |
        npx expo build:android -t app-bundle --non-interactive --release-channel default --config ./app.config.ts
        npx expo build:ios -t archive --release-channel default --config ./app.config.ts

    - name: Publish & build with Expo channel "next"
      if: endsWith(github.ref, '/next')
      env:
        EXPO_BUILDNUMBER: ${{ steps.version.outputs.buildNumber }}
        EXPO_VERSIONCODE: ${{ steps.version.outputs.versionCode }}
      run: |
        npx expo build:android -t app-bundle --non-interactive --release-channel next --config ./app.config.ts
        npx expo build:ios -t archive --release-channel next --config ./app.config.ts

    - name: Build 
      if: "!endsWith(github.ref, '/next') && !endsWith(github.ref, '/master')"
      env:
        EXPO_BUILDNUMBER: ${{ steps.version.outputs.buildNumber }}
        EXPO_VERSIONCODE: ${{ steps.version.outputs.versionCode }}
      run: |
        npx expo build:android -t app-bundle --non-interactive --release-channel pr --config ./app.config.ts
        npx expo build:ios -t archive --release-channel pr --config ./app.config.ts
