name: Expo CI

on:
  push:
    branches:
      - master
      - next

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout project repository
      uses: actions/checkout@v2

    - name: Setup kernel for react native, increase watchers
      run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install, build and test
      run: npm ci && npm test

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Login into Expo
      run: npx expo-cli login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}

    - name: Publish & build with Expo channel "default"
      if: endsWith(github.ref, '/master')
      run: | 
        npx expo build:android -t app-bundle --non-interactive --release-channel default

    - name: Publish & build with Expo channel "next"
      if: endsWith(github.ref, '/next')
      run: |
        npx expo build:android -t app-bundle --non-interactive --release-channel next
